# Generated by Django 2.0.6 on 2018-08-17 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180719_1234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='photo',
        ),
        migrations.AddField(
            model_name='customer',
            name='loginid',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='password',
            field=models.SlugField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
